name: nike
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: 5.4.0
  cached_network_image: ^3.3.1
  path_provider: 2.1.1
  equatable: 2.0.5
  bloc: 8.1.2
  flutter_bloc: 8.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/img/
  fonts:
    - family: yekan
      fonts:
        - asset: assets/fonts/yekanRegular.ttf
        - asset: assets/fonts/yekanMedium.ttf
        - asset: assets/fonts/yekanBold.ttf
